DROP TABLE user_account;
CREATE TABLE user_account -- because user is reserved
(
    id           UUID                         DEFAULT gen_random_uuid() PRIMARY KEY,
    email        VARCHAR(255) UNIQUE NOT NULL,
    avatar_url   VARCHAR(255),
    avatar_color VARCHAR(255),
    lastname     VARCHAR(255)        NOT NULL DEFAULT 'Ismeretlen',
    firstname    VARCHAR(255)        NOT NULL DEFAULT 'Személy',
    created_at   TIMESTAMPTZ                  DEFAULT NOW() NOT NULL,
    FOREIGN KEY (id) REFERENCES auth.users.id ON DELETE CASCADE
);

ALTER TABLE public.user_account ENABLE ROW LEVEL SECURITY;

DROP TABLE make;
CREATE OR REPLACE TABLE make
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name   TEXT    NOT NULL UNIQUE
);

ALTER TABLE public.make ENABLE ROW LEVEL SECURITY;

DROP TABLE model;
CREATE OR REPLACE TABLE model
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    make_id    INTEGER    NOT NULL,
    name       TEXT       NOT NULL,
    start_year VARCHAR(4) NOT NULL,
    end_year   VARCHAR(4),
    FOREIGN KEY (make_id) REFERENCES make (id) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (make_id, name)
);

ALTER TABLE public.model ENABLE ROW LEVEL SECURITY;

DROP TABLE car2;
CREATE OR REPLACE TABLE car2
(
    id         UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id   UUID                      NOT NULL,
    name       TEXT,
    model_id   INTEGER,
    model_year VARCHAR(4),
    image_url  VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES user_account (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (model_id) REFERENCES model (id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE public.car2 ENABLE ROW LEVEL SECURITY;

DROP TABLE odometer;
CREATE OR REPLACE TABLE odometer
(
    id          UUID       DEFAULT gen_random_uuid() PRIMARY KEY,
    car_id      UUID UNIQUE,                      -- 1-1
    value       BIGINT     DEFAULT 0    NOT NULL,
    measurement VARCHAR(6) DEFAULT 'km' NOT NULL, --{ 'km', 'mi' }
    FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.odometer ENABLE ROW LEVEL SECURITY;

DROP TABLE fuel_tank;
CREATE OR REPLACE TABLE fuel_tank
(
    id          UUID       DEFAULT gen_random_uuid() PRIMARY KEY,
    car_id      UUID UNIQUE            NOT NULL, -- 1-1
    type        VARCHAR(24)            NOT NULL, --{ 'PETROL', 'DIESEL', 'LPG', 'ELECTRIC' }
    capacity    BIGINT     DEFAULT 0   NOT NULL,
    value       BIGINT     DEFAULT 0   NOT NULL,
    measurement VARCHAR(3) DEFAULT 'l' NOT NULL, --{ 'l', 'gal' }
    FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE public.fuel_tank ENABLE ROW LEVEL SECURITY;

-- RLS policies
-- user_account – owner can see/modify own account
CREATE POLICY "user can view own account" ON public.user_account FOR SELECT TO authenticated USING ((SELECT auth.uid()) = id);
CREATE POLICY "user can insert own account" ON public.user_account FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "user can update own account" ON public.user_account FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = id) WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "user can delete own account" ON public.user_account FOR DELETE TO authenticated USING ((SELECT auth.uid()) = id);

-- make – readable by anyone, but only service_role can modify
CREATE POLICY "public can read makes" ON public.make FOR SELECT TO authenticated USING (true);
CREATE POLICY "service_role can modify makes" ON public.make FOR ALL TO service_role USING (true);

-- model – readable by anyone, but only service_role can modify
CREATE POLICY "public can read models" ON public.model FOR SELECT TO authenticated USING (true);
CREATE POLICY "service_role can modify models" ON public.model FOR ALL TO service_role USING (true);

-- car2 – owner‑only access
CREATE POLICY "car owner can view" ON public.car2 FOR SELECT TO authenticated USING ((SELECT auth.uid()) = owner_id);
CREATE POLICY "car owner can insert" ON public.car2 FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = owner_id);
CREATE POLICY "car owner can update" ON public.car2 FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = owner_id) WITH CHECK ((SELECT auth.uid()) = owner_id);
CREATE POLICY "car owner can delete" ON public.car2 FOR DELETE TO authenticated USING ((SELECT auth.uid()) = owner_id);

-- odometer – access via the linked car's owner
CREATE POLICY "odometer owner can view" ON public.odometer FOR SELECT TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "odometer owner can insert" ON public.odometer FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "odometer owner can update" ON public.odometer FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id)) WITH CHECK ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "odometer owner can delete" ON public.odometer FOR DELETE TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));

-- fuel_tank – access via the linked car's owner
CREATE POLICY "fuel_tank owner can view" ON public.fuel_tank FOR SELECT TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "fuel_tank owner can insert" ON public.fuel_tank FOR INSERT TO authenticated WITH CHECK ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "fuel_tank owner can update" ON public.fuel_tank FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id)) WITH CHECK ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));
CREATE POLICY "fuel_tank owner can delete" ON public.fuel_tank FOR DELETE TO authenticated USING ((SELECT auth.uid()) = (SELECT owner_id FROM public.car2 WHERE id = car_id));

-- Indexes to speed up the look‑ups used in the policies
CREATE INDEX idx_user_account_id ON public.user_account (id);
CREATE INDEX idx_car2_owner_id ON public.car2 (owner_id);
CREATE INDEX idx_odometer_car_id ON public.odometer (car_id);
CREATE INDEX idx_fuel_tank_car_id ON public.fuel_tank (car_id);


DROP PUBLICATION powersync;
CREATE PUBLICATION powersync FOR ALL TABLES;

CREATE ROLE powersync_role WITH REPLICATION BYPASSRLS LOGIN PASSWORD 'JECY6oX9mnfvriGBI6HaCpdy7MF6mA';

-- Set up permissions for the newly created role
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO powersync_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO powersync_role;

-- Enable logical replication
ALTER SYSTEM SET wal_level = logical;