export enum ServiceItemTypeEnum {
    TRANSMISSION_FLUID = "TRANSMISSION_FLUID",
    FUEL_FILTER = "FUEL_FILTER",
    BRAKE_FLUID = "BRAKE_FLUID",
    LIGHT_BULB = "LIGHT_BULB",
    WIPER_BLADES = "WIPER_BLADES",
    DIAGNOSTICS = "DIAGNOSTICS",
    OIL = "OIL",
    COOLANT = "COOLANT",
    CABIN_FILTER = "CABIN_FILTER",
    OIL_FILTER = "OIL_FILTER",
    BRAKE_DISCS = "BRAKE_DISCS",
    BATTERY = "BATTERY",
    SPARK_PLUGS = "SPARK_PLUGS",
    SOFTWARE_UPDATE = "SOFTWARE_UPDATE",
    BRAKE_PADS = "BRAKE_PADS",
    TIRES = "TIRES",
    AIR_FILTER = "AIR_FILTER"
}