export enum ServiceTypeEnum {
    SMALL_SERVICE = "SMALL_SERVICE",
    MAJOR_SERVICE = "MAJOR_SERVICE",
    REPAIR = "REPAIR",
    HOME_MAINTENANCE = "HOME_MAINTENANCE",
    INSPECTION = "INSPECTION",
    DIAGNOSTICS = "DIAGNOSTICS",
    TIRE_CHANGE = "TIRE_CHANGE",
    OTHER = "OTHER"
}