import {
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    SUPABASE_BUCKET,
    RESEND_API_KEY,
    POWERSYNC_URL,
    GOOGLE_WEBCLIENTID
} from "@env";

export const BaseConfig = {
    SUPABASE_URL: SUPABASE_URL,
    SUPABASE_ANON_KEY: SUPABASE_ANON_KEY,
    SUPABASE_BUCKET: SUPABASE_BUCKET,
    RESEND_API_KEY: RESEND_API_KEY,
    POWERSYNC_URL: POWERSYNC_URL,
    GOOGLE_WEBCLIENTID: GOOGLE_WEBCLIENTID
}