import { COLORS } from "./colors.ts";

export const ICON_NAMES = {
    close: "close",
    email: "email-outline",
    password: "lock-outline",
    user: "account-outline",
    checkMark: "check-circle-outline",
    eye: "eye-outline",
    eyeOff: "eye-off-outline",
    pencil: "pencil-outline",
    rightArrowHead: "chevron-right",
    rightArrow: "arrow-right",
    leftArrowHead: "chevron-left",
    leftArrow: "arrow-left",
    downArrowHead: "chevron-down",
    upArrowHead: "chevron-up",
    info: "information-outline",
    destinationPointMarker: "map-marker",
    startingPointMarker: "map-marker-outline",
    clock: "clock-time-seven-outline",
    homeOutline: "home-outline",
    home: "home",
    notebookOutline: "notebook-outline",
    notebook: "notebook",
    serviceOutline: "wrench-outline",
    service: "wrench",
    expensesOutline: "account-cash-outline",
    expenses: "account-cash",
    car: "car-outline",
    nametag: "tag-text-outline",
    odometer: "gauge",
    search: "magnify",
    addImage: "image-plus",
    image: "image-outline",
    trashCan: "delete-outline",
    calendar: "calendar-range-outline",
    reset: "refresh",
    upload: "upload-outline",
    fuelPump: "gas-station-outline",
    fuelCan: "fuel",
    settings: "cog-outline",
    signOut: "logout",
    swap: "swap-horizontal",
    add: "plus",
    receipt: "receipt-text-outline",
    road: "road-variant"
};

export const ICON_COLORS = {
    default: COLORS.white,
    good: COLORS.greenLight,
    wrong: "red",
    active: COLORS.white,
    inactive: COLORS.gray1
};
