import { COLORS } from "./colors.ts";

export const ICON_NAMES = {
    close: "close",
    email: "email-outline",
    password: "lock-outline",
    user: "account-outline",
    checkMark: "check-circle-outline",
    check: "check",
    eye: "eye-outline",
    eyeOff: "eye-off-outline",
    pencil: "pencil-outline",
    rightArrowHead: "chevron-right",
    rightArrow: "arrow-right",
    leftArrowHead: "chevron-left",
    leftArrow: "arrow-left",
    downArrowHead: "chevron-down",
    downArrow: "arrow-down",
    upArrowHead: "chevron-up",
    upArrow: "arrow-up",
    info: "information-outline",
    destinationPointMarker: "map-marker",
    startingPointMarker: "map-marker-outline",
    clock: "clock-time-seven-outline",
    homeOutline: "home-outline",
    home: "home",
    notebookOutline: "notebook-outline",
    notebook: "notebook",
    serviceOutline: "wrench-outline",
    service: "wrench",
    expensesOutline: "account-cash-outline",
    expenses: "account-cash",
    car: "car-outline",
    carOff: "car-off",
    nametag: "tag-text-outline",
    odometer: "speedometer", //gauge
    odometerLow: "speedometer-slow",
    search: "magnify",
    addImage: "image-plus",
    image: "image-outline",
    trashCan: "delete-outline",
    calendar: "calendar-range-outline",
    reset: "refresh",
    upload: "tray-arrow-up",
    cameraPlus: "camera-plus-outline",
    fuelPump: "gas-station",
    fuelCan: "fuel",
    settings: "cog-outline",
    signOut: "logout",
    swap: "swap-horizontal",
    add: "plus",
    receipt: "receipt-text-outline",
    road: "road-variant",
    carWash: "car-wash",
    parking: "parking",
    vehicleInspection: "car-search",
    insurance: "shield-car",
    registration: "clipboard-text-multiple",
    note: "text",
    money: "cash",
    expenseItem: "invoice-text-multiple-outline",
    passenger: "account-outline",
    passengers: "account-multiple-outline",
    mapMarkers: "map-marker-multiple-outline",
    statistics: "finance",
    gestureTap: "gesture-tap"
} as const;

export const SERVICE_ICONS = {
    SMALL_SERVICE: "wrench-outline",
    MAJOR_SERVICE: "tools",
    REPAIR: "car-wrench",
    HOME_MAINTENANCE: "home",
    INSPECTION: "clipboard-check-outline",
    DIAGNOSTICS: "car-search-outline",
    TIRE_CHANGE: "tire",
    OTHER: "dots-horizontal-circle-outline"
} as const;

export const SERVICE_ITEM_ICONS = {
    TRANSMISSION_FLUID: "car-shift-pattern",
    FUEL_FILTER: "filter-outline",
    BRAKE_FLUID: "car-brake-fluid-level",
    LIGHT_BULB: "lightbulb-outline",
    WIPER_BLADES: "car-wash",
    DIAGNOSTICS: "car-search-outline",
    OIL: "oil",
    COOLANT: "coolant-temperature",
    CABIN_FILTER: "air-filter",
    OIL_FILTER: "oil-filter",
    BRAKE_DISCS: "car-brake-disc",
    BATTERY: "car-battery",
    SPARK_PLUGS: "car-spark-plug",
    SOFTWARE_UPDATE: "update",
    BRAKE_PADS: "shield-half-full",
    TIRES: "tire",
    AIR_FILTER: "air-filter"
} as const;

export const ICON_COLORS = {
    default: COLORS.white,
    good: COLORS.greenLight,
    wrong: "red",
    active: COLORS.white,
    inactive: COLORS.gray1
};
