CREATE TABLE user_account -- because user is reserved
(
    id           UUID                         DEFAULT gen_random_uuid() PRIMARY KEY,
    email        VARCHAR(255) UNIQUE NOT NULL,
    password     TEXT                NOT NULL,
    avatar_url   VARCHAR(255),
    avatar_color VARCHAR(255),
    lastname     VARCHAR(255)        NOT NULL DEFAULT 'Ismeretlen',
    firstname    VARCHAR(255)        NOT NULL DEFAULT 'Személy',
    created_at   TIMESTAMPTZ                  DEFAULT NOW() NOT NULL
);

CREATE TABLE make
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name   TEXT    NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE model
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    make_id    INTEGER    NOT NULL,
    name       TEXT       NOT NULL,
    start_year VARCHAR(4) NOT NULL,
    end_year   VARCHAR(4),
    active     BOOLEAN    NOT NULL DEFAULT true,
    FOREIGN KEY (make_id) REFERENCES make (id) ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE (make_id, name)
);

CREATE TABLE car
(
    id         UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id   UUID                      NOT NULL,
    name       TEXT,
    model_id   INTEGER,
    model_year VARCHAR(4),
    image_url  VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES user_account (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (model_id) REFERENCES model (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE odometer
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    car_id      UUID,
    value       BIGINT DEFAULT 0,
    measurement TEXT   DEFAULT 'km', --{ 'km', 'mi' }
    FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE fuel_tank
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    car_id      UUID,
    type        TEXT,
    tankSize    BIGINT DEFAULT 0,
    value       BIGINT DEFAULT 0,
    measurement TEXT   DEFAULT 'L', --{ 'L', 'D', 'E' }
    FOREIGN KEY (car_id) REFERENCES car (id) ON UPDATE CASCADE ON DELETE CASCADE
);