import {
    BACKEND_API_BASE_URL,
    CAR_BRANDS_VERSION,
    GOOGLE_WEBCLIENTID,
    LOCAL_STORAGE_KEY_CAR_BRANDS_VERSION,
    LOCAL_STORAGE_KEY_NOT_VERIFIED_USER,
    LOCAL_STORAGE_KEY_SELECTED_CAR_INDEX,
    POWERSYNC_URL,
    RESEND_API_KEY,
    SECURE_STORAGE_KEY_REFRESH_TOKEN,
    SECURE_STORAGE_KEY_TOKEN,
    SUPABASE_ANON_KEY,
    SUPABASE_BUCKET,
    SUPABASE_URL
} from "@env";

export const BaseConfig = {
    SUPABASE_URL: SUPABASE_URL,
    SUPABASE_ANON_KEY: SUPABASE_ANON_KEY,
    SUPABASE_BUCKET: SUPABASE_BUCKET,
    RESEND_API_KEY: RESEND_API_KEY,
    POWERSYNC_URL: POWERSYNC_URL,
    GOOGLE_WEBCLIENTID: GOOGLE_WEBCLIENTID,
    LOCAL_STORAGE_KEY_SELECTED_CAR_INDEX: LOCAL_STORAGE_KEY_SELECTED_CAR_INDEX,
    LOCAL_STORAGE_KEY_NOT_VERIFIED_USER: LOCAL_STORAGE_KEY_NOT_VERIFIED_USER,
    LOCAL_STORAGE_KEY_CAR_BRANDS_VERSION: LOCAL_STORAGE_KEY_CAR_BRANDS_VERSION,
    CAR_BRANDS_VERSION: CAR_BRANDS_VERSION,
    BACKEND_API_BASE_URL: BACKEND_API_BASE_URL,
    SECURE_STORAGE_KEY_TOKEN: SECURE_STORAGE_KEY_TOKEN,
    SECURE_STORAGE_KEY_REFRESH_TOKEN: SECURE_STORAGE_KEY_REFRESH_TOKEN
};