type Config = {
    SCRAPER_API_PORT: number
    SCRAPER_CAR_MAKES_URL: string
    SCRAPER_CAR_MAKE_MODELS_BASE_URL: string
    CHROME_EXECUTABLE_PATH: string
    RABBITMQ_URL: string
    RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME: string
    RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME: string
};

const CONFIG: Config = {
    SCRAPER_API_PORT: Number(process.env.SCRAPER_API_PORT),
    SCRAPER_CAR_MAKES_URL: process.env.SCRAPER_CAR_MAKES_URL || "",
    SCRAPER_CAR_MAKE_MODELS_BASE_URL: process.env.SCRAPER_CAR_MAKE_MODELS_BASE_URL || "",
    CHROME_EXECUTABLE_PATH: process.env.CHROME_EXECUTABLE_PATH || "/usr/bin/google-chrome",
    RABBITMQ_URL: process.env.RABBITMQ_URL || "",
    RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME: process.env.RABBITMQ_SCRAPER_CAR_MAKE_QUEUE_NAME || "",
    RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME: process.env.RABBITMQ_SCRAPER_CAR_MODEL_QUEUE_NAME || ""
};

export default CONFIG;
