import {
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    SUPABASE_BUCKET,
    RESEND_API_KEY,
    POWERSYNC_URL,
} from "@env";

export const BaseConfig = {
    SUPABASE_URL,
    SUPABASE_ANON_KEY,
    SUPABASE_BUCKET,
    RESEND_API_KEY,
    POWERSYNC_URL,
}